[features]
seeds = false
skip-lint = false
[programs.localnet]
r24_anchor_gofundme = "4sexL2C9M3xM69EzMwFEN4yTkm3qWmJpBu83KXyjsmqJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
